### ISSUE TITLE
A new logo

### ISSUE THREAD

**Issue by mohandas-pai** [mohandas-pai/German-Lernen#1]
The logo i designed doesnt catch the eye. Want a new logo that fits the "Education". Having it in the colours of the German National Flag is a big plus.

**Comment by arsundram** [comment]
I would love to work on this logo! @mohandas-pai 
If available, can you assign this to me?

**Comment by mohandas-pai** [comment]
That amazing logo you desined for Bricks.. i'll be very happy that you will design one for this as well.
