### ISSUE TITLE
Need app description which will be updated on the play store

### ISSUE THREAD

**Issue by mohandas-pai** [mohandas-pai/German-Lernen#4]
The app (link in readme) needs a very informative description. Edit it in the readme and i'll do the same changes in Playstore.
It would be good if you already know german so that you can associate with the app. Please install the app and go through it before making any chages to readme.

**Comment by rdmchr** [comment]
I'm a native German speaker and I would like to help fix this issue. Do you still need help with it?

**Comment by mohandas-pai** [comment]
Yes.. could you please translate the readme file from "Ever wanted to..." till "i will fix/add them" in simple german?

**Comment by rdmchr** [comment]
Do you want me to create a new README.md file that's in German or should I just append the German part under the English part?

**Comment by mohandas-pai** [comment]
You can just append below it. If you want to add few sentences that is also fine, you can download the app in play store and check it out
